### PR TITLE
adding automatic event handling as well as multiple request support

### PR DESCRIPTION
**Pull request by nopol**

### CODE REVIEW

**Comment by eddyystop** [comment]
You need to run `npm run test` successfully. The tests are throwing 59 errors.

**Comment by nopol** [comment]
Of course it does. I changed everything and removed a lot of the stuff. I'll redesign the tests and push the changes as soon as possible. I just want to share the new features back to you as well. We are using your module and advanced the features to archive multi-handling of requests as well as automatically evant handling via socket.io.

**Comment by nopol** [comment]
added tests for event-handling

**Comment by eddyystop** [comment]
Partially related to https://github.com/eddyystop/feathers-reduxify-services/issues/2

**Comment by eddyystop** [comment]
FYI, I'm seeing how this would integrate with some offline-first I've worked on.

**Comment by eddyystop** [comment]
You've obviously put some good thought into your changes, and thank you for them. There however are some issues with the mechanics of the PR, itemized below.

I'll look at the changes individually so the repo remains backward compatible and consistent.

---

I have no issues with you forking the repo, but this is not what you include in a PR.
```text
-  "url": "git+https://github.com/eddyystop/feathers-reduxify-services.git"
+ "url": "git+https://github.com/ILS-Gmbh/feathers-reduxify-services.git"
-  "url": "https://github.com/eddyystop/feathers-reduxify-services/issues"
+ "url": "https://github.com/ILS-Gmbh/feathers-reduxify-services/issues"
-  "homepage": "https://github.com/eddyystop/feathers-reduxify-services#readme",
+  "homepage": "https://github.com/ILS-Gmbh/feathers-reduxify-services#readme",
```

`getServicesStatus` has been removed, affecting people using this repo, myself included.
There are no docs on  @`automaticDispatchEvents`.
All of lowdash is required while this repo does not do tree-shaking.

**Comment by eddyystop** [comment]
Replication engines generally maintain a near realtime, local copy of (some of) the records in a service on the server. `feathers-reduxify-services` now provides an interface which you can use to interface replication engines with the Redux state for the service.

This interface updates the new state property `store` which has been added to the previous ones: isError, isLoading, isSaving, isFinihsed, data and queryResult.

`feathers-offline-realtime` is the official Feathersjs realtime replication engine. Please read its README.

It can be interfaced with `feathers-reduxify-services` as follows:
```javascript
import reduxifyServices from 'feathers-reduxify-services';
import Realtime from 'feathers-offline-realtime';

const services = reduxifyServices(app, ['messages', ...]);
const store = applyMiddleware( ... , messages: services.messages.reducer }));

const messagesRealtime = new Realtime(feathersApp.service('/messages'));

messagesRealtime.on('events', (records, last) => {
  store.dispatch(services.messages.store({ connected: messagesRealtime.connected, last, records }));
});
```

This would create the state:
```javascript
state.messages.store = {
  connected: boolean, // if replication engine still listening to server
  last: { activity, eventName, record }, // last activity. See feathers-offline-realtime
  records: [ objects ], // the near realtime contents of the remote service
};
```

In the next few days this repo will be brought into Feathersjs itself as `feathers-redux` and the repo itself will be deprecated

**Comment by eddyystop** [comment]
These new features are a super set of this PR, which hence is being closed.

Please try the new repo as
- It snapshots the initial contents of the remote service.
- Allows replication of only some of the records, e.g. those for one username from a table containing data for all usernames.
- Its handles "illogical" created, updated, patched events by mutating the store properly.
- Its being brought into Feathersjs in the next few days.

Please let me know of your experience.

Thanks.

**Pull request closed without merging**
